import { Inter } from 'next/font/google'
import PropTypes from 'prop-types'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div lang="en">
      <duv className="h-full w-full">{children}</duv>
    </div>
  )
}

RootLayout.propTypes = {
  children: PropTypes.isRequired,
}
